name = "tmp-cloud"
type = "javascript"
account_id = "5d4a9e31fb626889b130410ed0590d86"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "tmp-cloud-r2"
